version: "3"
services:
  db:
    image: mysql:8.0.32
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    volumes:
      - .:/demo_python
volumes:
  db-data:
